/* 
  Sync latest movies from VidSrc-embed into a local TS data file.
  Run with:
    npx ts-node scripts/sync-vidsrc-latest.ts
  or compile and run with node:
    npx tsc scripts/sync-vidsrc-latest.ts && node scripts/sync-vidsrc-latest.js
*/

// We rely on global fetch (Node 18+). If missing, user can install node-fetch.

type VidsrcMovie = {
  imdb_id: string;
  tmdb_id: string;
  title: string;
  quality: string;
  time_added: string;
  embed_url: string;
  embed_url_tmdb: string;
};

type VidsrcPage = {
  result: VidsrcMovie[];
  pages: number;
};

import { writeFileSync } from "fs";
import { join } from "path";

async function fetchPage(page: number): Promise<VidsrcPage | null> {
  const url = `https://vidsrc-embed.ru/movies/latest/page-${page}.json`;
  console.log(`Fetching ${url}`);
  const res = await fetch(url);
  if (!res.ok) {
    console.warn(`  -> failed with status ${res.status}`);
    return null;
  }
  const json = (await res.json()) as VidsrcPage;
  return json;
}

async function main() {
  const allMovies: VidsrcMovie[] = [];

  // First page to know total pages
  const first = await fetchPage(1);
  if (!first) {
    console.error("Failed to fetch first page from VidSrc-embed.");
    process.exit(1);
  }

  allMovies.push(...first.result);
  const totalPages = first.pages || 1;
  console.log(`Total pages reported by API: ${totalPages}`);

  // Safety cap so we don't hammer the API too hard in one go.
  const MAX_PAGES = totalPages;

  for (let p = 2; p <= MAX_PAGES; p++) {
    const page = await fetchPage(p);
    if (!page) continue;
    allMovies.push(...page.result);
  }

  console.log(`Collected ${allMovies.length} movies from VidSrc-embed.`);

  // Build a minimal TS data file we can import in the app.
  const targetPath = join(
    process.cwd(),
    "app",
    "data",
    "vidsrcLatestMovies.ts"
  );

  const header = `// Auto-generated by scripts/sync-vidsrc-latest.ts\n` +
    `// Source: https://vidsrc-embed.ru/movies/latest/page-*.json\n` +
    `// Total movies: ${allMovies.length}\n\n` +
    `export interface VidsrcLatestMovie {\n` +
    `  imdb_id: string;\n` +
    `  tmdb_id: string;\n` +
    `  title: string;\n` +
    `  quality: string;\n` +
    `  time_added: string;\n` +
    `  embed_url: string;\n` +
    `  embed_url_tmdb: string;\n` +
    `}\n\n` +
    `export const VID_SRC_LATEST_MOVIES: VidsrcLatestMovie[] = [\n`;

  const body = allMovies
    .map((m) => {
      const safeTitle = m.title
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/`/g, "\\`");
      return `  {\n` +
        `    imdb_id: "${m.imdb_id}",\n` +
        `    tmdb_id: "${m.tmdb_id}",\n` +
        `    title: "${safeTitle}",\n` +
        `    quality: "${m.quality}",\n` +
        `    time_added: "${m.time_added}",\n` +
        `    embed_url: "${m.embed_url}",\n` +
        `    embed_url_tmdb: "${m.embed_url_tmdb}",\n` +
        `  }`;
    })
    .join(",\n");

  const footer = `\n];\n`;

  writeFileSync(targetPath, header + body + footer, "utf8");
  console.log(`Wrote ${targetPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

